# Generated by Django 5.2.1 on 2025-05-30 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=250)),
                ('crop_description', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(help_text='eg: kg, bags', max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvested_date', models.DateField(help_text='what is the date you harvested your crop')),
                ('img', models.ImageField(upload_to='cropImage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
