# Generated by Django 5.2.1 on 2025-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croplisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplisting',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT OF STOCK', 'Out of Stock')], default='Available', max_length=24),
        ),
    ]
