# Generated by Django 5.2.1 on 2025-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croplisting', '0002_croplisting_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplisting',
            name='is_Organic',
            field=models.BooleanField(default=True),
        ),
    ]
