# Generated by Django 5.2.1 on 2025-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
